### ISSUE TITLE
need a Guide to install xact on steam deck

### ISSUE THREAD

**Issue by AnTrellc96** [framilano/CallofDutyAltLauncher#1]
Hello! i have bo1 installed but im having some trouble installing xact through Protontricks. What do I do?

**Comment by AnTrellc96** [comment]
Hello! i have bo1 installed but im having some trouble installing xact through Protontricks. What do I do?

**Comment by framilano** [comment]
Hi @AnTrellc96 you need to install protontricks from Desktop Mode using Discovery.
Proton Tricks will list you how many proton bottles you have currently, selecte the one you're using with PlutoniumDeckLauncher and select the install library option, look for xact and let it do its stuff.
